# Generated by Django 4.2.1 on 2023-06-26 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='views',
        ),
        migrations.AddField(
            model_name='software',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='viewed_software', to=settings.AUTH_USER_MODEL),
        ),
    ]
