# Generated by Django 4.2.1 on 2023-06-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalapp', '0003_software_demo_available_software_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
