# Generated by Django 4.2.1 on 2023-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalapp', '0005_subscription_stripe_product_id_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
