# Generated by Django 4.2.1 on 2023-06-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalapp', '0007_alter_subscription_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='subscription',
        ),
    ]
