# Generated by Django 4.2.1 on 2023-06-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalapp', '0009_software_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='subscription',
        ),
        migrations.AddField(
            model_name='software',
            name='subscription',
            field=models.ManyToManyField(default=4, to='catalapp.subscription'),
        ),
    ]
