# Generated by Django 4.2.1 on 2023-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalapp', '0011_alter_software_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='subscription',
            field=models.ManyToManyField(default=4, to='catalapp.subscription'),
        ),
    ]
