# Generated by Django 4.2.1 on 2023-07-01 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalapp', '0013_payment_remaining_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('additional_info', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, upload_to='user_request_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_under_review', models.BooleanField(default=True)),
                ('industry_specific', models.BooleanField(default=False)),
                ('desired_features', models.TextField(blank=True)),
                ('technologies', models.ManyToManyField(to='catalapp.technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
