# Generated by Django 4.2.1 on 2023-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalapp', '0014_technology_userrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='industry_specific',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='industry_specific',
            field=models.ManyToManyField(to='catalapp.industry'),
        ),
    ]
