# Generated by Django 4.2.1 on 2023-07-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalapp', '0015_industry_userrequest_is_rejected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
