# Generated by Django 4.2.1 on 2023-07-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalapp', '0016_techstacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='techstacks',
            field=models.ManyToManyField(to='catalapp.techstacklist'),
        ),
    ]
